# Generated by Django 2.2.3 on 2019-07-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='project', max_length=100),
        ),
        migrations.AddField(
            model_name='puser',
            name='type',
            field=models.CharField(default='partner', max_length=100),
        ),
    ]
