# Generated by Django 2.2.3 on 2019-07-17 04:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
